In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
from google.colab import files
dataset = files.upload()

Saving loan_small.csv to loan_small.csv

In [ ]:
df=pd.read_csv('loan_small.csv')

In [ ]:
df

,Loan_ID,Gender,ApplicantIncome,CoapplicantIncome,LoanAmount,Area,Loan_Status
0,LP001002,NaN,5849.0,0.0,NaN,urban,Y
1,LP001003,Male,4583.0,NaN,128.0,semi,N
2,LP001005,Male,3000.0,0.0,66.0,NaN,Y
3,LP001006,Female,2583.0,2358.0,120.0,semi,NaN
4,LP001008,Male,NaN,0.0,141.0,urban,Y
5,LP001011,Male,5417.0,4196.0,267.0,semi,Y
6,LP001013,Male,2333.0,1516.0,NaN,rural,Y
7,LP001014,Female,3036.0,2504.0,158.0,semi,N
8,LP001018,Male,4006.0,1526.0,168.0,rural,Y
9,LP001020,Male,12841.0,10968.0,349.0,semi,N
10,LP001024,Female,3200.0,700.0,70.0,urban,Y
11,LP001027,Male,2500.0,1840.0,109.0,urban,Y
12,LP001028,Female,NaN,8106.0,NaN,urban,Y
13,LP001029,Male,1853.0,2840.0,114.0,urban,N
14,LP001030,Male,1299.0,1086.0,17.0,semi,Y
15,LP001032,Male,4950.0,0.0,125.0,semi,Y

In [ ]:
df.shape

(16, 7)

In [ ]:
df.head()

,Loan_ID,Gender,ApplicantIncome,CoapplicantIncome,LoanAmount,Area,Loan_Status
0,LP001002,NaN,5849.0,0.0,NaN,urban,Y
1,LP001003,Male,4583.0,NaN,128.0,semi,N
2,LP001005,Male,3000.0,0.0,66.0,NaN,Y
3,LP001006,Female,2583.0,2358.0,120.0,semi,NaN
4,LP001008,Male,NaN,0.0,141.0,urban,Y

In [ ]:
df.tail()

,Loan_ID,Gender,ApplicantIncome,CoapplicantIncome,LoanAmount,Area,Loan_Status
11,LP001027,Male,2500.0,1840.0,109.0,urban,Y
12,LP001028,Female,NaN,8106.0,NaN,urban,Y
13,LP001029,Male,1853.0,2840.0,114.0,urban,N
14,LP001030,Male,1299.0,1086.0,17.0,semi,Y
15,LP001032,Male,4950.0,0.0,125.0,semi,Y

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            16 non-null     object
 1   Gender             15 non-null     object
 2   ApplicantIncome    14 non-null     float64
 3   CoapplicantIncome  15 non-null     float64
 4   LoanAmount         13 non-null     float64
 5   Area               15 non-null     object
 6   Loan_Status        15 non-null     object
dtypes: float64(3), object(4)
memory usage: 1.0+ KB

In [ ]:
df.describe()

       ApplicantIncome  CoapplicantIncome  LoanAmount
count        14.000000          15.000000   13.000000
mean       4103.571429        2509.333333  140.923077
std        2858.096481        3147.982090   86.032418
min        1299.000000           0.000000   17.000000
25%        2520.750000         350.000000  109.000000
50%        3118.000000        1526.000000  125.000000
75%        4858.250000        2672.000000  158.000000
max       12841.000000       10968.000000  349.000000

##Data Cleaning

##Missig Value

In [ ]:
df.isnull().sum()

Loan_ID              0
Gender               1
ApplicantIncome      2
CoapplicantIncome    1
LoanAmount           3
Area                 1
Loan_Status          1
dtype: int64

Here 'Loan_Status' is considered as target variable. so first we want clear missing values in target varibale by using function **'dropna()'**.

> (If missing occur from target variables, then just drop the records)

In [ ]:
data=df['Loan_Status'].dropna()

In [ ]:
data

0     Y
1     N
2     Y
4     Y
5     Y
6     Y
7     N
8     Y
9     N
10    Y
11    Y
12    Y
13    N
14    Y
15    Y
Name: Loan_Status, dtype: object

In [ ]:
df

,Loan_ID,Gender,ApplicantIncome,CoapplicantIncome,LoanAmount,Area,Loan_Status
0,LP001002,NaN,5849.0,0.0,NaN,urban,Y
1,LP001003,Male,4583.0,NaN,128.0,semi,N
2,LP001005,Male,3000.0,0.0,66.0,NaN,Y
3,LP001006,Female,2583.0,2358.0,120.0,semi,NaN
4,LP001008,Male,NaN,0.0,141.0,urban,Y
5,LP001011,Male,5417.0,4196.0,267.0,semi,Y
6,LP001013,Male,2333.0,1516.0,NaN,rural,Y
7,LP001014,Female,3036.0,2504.0,158.0,semi,N
8,LP001018,Male,4006.0,1526.0,168.0,rural,Y
9,LP001020,Male,12841.0,10968.0,349.0,semi,N
10,LP001024,Female,3200.0,700.0,70.0,urban,Y
11,LP001027,Male,2500.0,1840.0,109.0,urban,Y
12,LP001028,Female,NaN,8106.0,NaN,urban,Y
13,LP001029,Male,1853.0,2840.0,114.0,urban,N
14,LP001030,Male,1299.0,1086.0,17.0,semi,Y
15,LP001032,Male,4950.0,0.0,125.0,semi,Y

In [ ]:
df.isnull().sum()

Loan_ID              0
Gender               1
ApplicantIncome      2
CoapplicantIncome    1
LoanAmount           3
Area                 1
Loan_Status          1
dtype: int64